server:
  port: 8080

spring:
  application:
    name: mymo-api

  # H2 Database 설정
  datasource:
    url: jdbc:h2:mem:mymo-db-test # mem : 메모리에 저장, 서버 끄면 데이터 사라짐, file : 파일에 저장
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true # 웹(localhost:8080/h2-console)에서 DB 확인 가능

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update # 엔티티 수정 시 DB 테이블 자동 업데이트
    show-sql: true # 실행되는 SQL 로그 출력
    properties:
      hibernate:
        format_sql: true # SQL을 가독성 좋게 정렬해서 출력
        highlight_sql: true # 가독성 증가
  # Java 21 가상 스레드 활성화
  threads:
    virtual:
      enabled: false